export const data = [
  {
    consumerName: "Raghuvendra Raga",
    assets: {
      total: "₹35,342",
      gold: "50.54g",
      silver: "34.2g",
      money: "₹242.5",
    },
    kycStatus: "Done",
    fieldExec: "Arun Jha",
    associate: "Anika Singh",
    zone: "South",
    accountType: "Business",
    tpa: "9876543210@trucard",
    notif:3
  },
  {
    consumerName: "Consumer 1",
    assets: {
      total: "₹34666",
      gold: "72.78g",
      silver: "21.39g",
      money: "₹278.18",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 1",
    associate: "Associate 1",
    zone: "South",
    accountType: "Business",
    tpa: "6482906667@trucard",
  },
  {
    consumerName: "Consumer 2",
    assets: {
      total: "₹4160",
      gold: "56.24g",
      silver: "4.90g",
      money: "₹53.03",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 2",
    associate: "Associate 2",
    zone: "North",
    accountType: "Personal",
    tpa: "7008055081@trucard",
    notif:1
  },
  {
    consumerName: "Consumer 3",
    assets: {
      total: "₹18609",
      gold: "99.24g",
      silver: "47.36g",
      money: "₹58.28",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 3",
    associate: "Associate 3",
    zone: "South",
    accountType: "Business",
    tpa: "2163883264@trucard",
  },
  {
    consumerName: "Consumer 4",
    assets: {
      total: "₹8274",
      gold: "29.81g",
      silver: "38.48g",
      money: "₹69.09",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 4",
    associate: "Associate 4",
    zone: "North",
    accountType: "Personal",
    tpa: "2598446184@trucard",
  },
  {
    consumerName: "Consumer 5",
    assets: {
      total: "₹46222",
      gold: "72.55g",
      silver: "20.42g",
      money: "₹490.98",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 5",
    associate: "Associate 5",
    zone: "South",
    accountType: "Business",
    tpa: "9530764072@trucard",
    notif:5
  },
  {
    consumerName: "Consumer 6",
    assets: {
      total: "₹13368",
      gold: "4.73g",
      silver: "47.35g",
      money: "₹285.70",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 6",
    associate: "Associate 6",
    zone: "North",
    accountType: "Personal",
    tpa: "8589291254@trucard",
  },
  {
    consumerName: "Consumer 7",
    assets: {
      total: "₹19369",
      gold: "29.98g",
      silver: "49.63g",
      money: "₹275.92",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 7",
    associate: "Associate 7",
    zone: "South",
    accountType: "Business",
    tpa: "297906943@trucard",
  },
  {
    consumerName: "Consumer 8",
    assets: {
      total: "₹46087",
      gold: "82.20g",
      silver: "38.01g",
      money: "₹419.19",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 8",
    associate: "Associate 8",
    zone: "North",
    accountType: "Personal",
    tpa: "3229936689@trucard",
    notif:2
  },
  {
    consumerName: "Consumer 9",
    assets: {
      total: "₹23235",
      gold: "27.65g",
      silver: "25.35g",
      money: "₹65.72",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 9",
    associate: "Associate 9",
    zone: "South",
    accountType: "Business",
    tpa: "3820498891@trucard",
  },
  {
    consumerName: "Consumer 10",
    assets: {
      total: "₹1678",
      gold: "10.53g",
      silver: "29.52g",
      money: "₹214.72",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 10",
    associate: "Associate 10",
    zone: "North",
    accountType: "Personal",
    tpa: "7081693780@trucard",
  },
  {
    consumerName: "Consumer 11",
    assets: {
      total: "₹41265",
      gold: "36.57g",
      silver: "22.33g",
      money: "₹305.65",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 11",
    associate: "Associate 11",
    zone: "South",
    accountType: "Business",
    tpa: "1813472212@trucard",
  },
  {
    consumerName: "Consumer 12",
    assets: {
      total: "₹5045",
      gold: "0.95g",
      silver: "1.30g",
      money: "₹209.71",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 12",
    associate: "Associate 12",
    zone: "North",
    accountType: "Personal",
    tpa: "8534272570@trucard",
  },
  {
    consumerName: "Consumer 13",
    assets: {
      total: "₹10423",
      gold: "83.68g",
      silver: "20.71g",
      money: "₹373.26",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 13",
    associate: "Associate 13",
    zone: "South",
    accountType: "Business",
    tpa: "8062215484@trucard",
  },
  {
    consumerName: "Consumer 14",
    assets: {
      total: "₹45159",
      gold: "27.67g",
      silver: "31.40g",
      money: "₹325.49",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 14",
    associate: "Associate 14",
    zone: "North",
    accountType: "Personal",
    tpa: "7129777299@trucard",
  },
  {
    consumerName: "Consumer 15",
    assets: {
      total: "₹44308",
      gold: "23.63g",
      silver: "28.73g",
      money: "₹0.34",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 15",
    associate: "Associate 15",
    zone: "South",
    accountType: "Business",
    tpa: "5923100730@trucard",
  },
  {
    consumerName: "Consumer 16",
    assets: {
      total: "₹21116",
      gold: "7.62g",
      silver: "36.01g",
      money: "₹197.80",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 16",
    associate: "Associate 16",
    zone: "North",
    accountType: "Personal",
    tpa: "1086977454@trucard",
  },
  {
    consumerName: "Consumer 17",
    assets: {
      total: "₹4940",
      gold: "93.76g",
      silver: "7.16g",
      money: "₹15.15",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 17",
    associate: "Associate 17",
    zone: "South",
    accountType: "Business",
    tpa: "725529426@trucard",
  },
  {
    consumerName: "Consumer 18",
    assets: {
      total: "₹46516",
      gold: "51.56g",
      silver: "47.31g",
      money: "₹9.00",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 18",
    associate: "Associate 18",
    zone: "North",
    accountType: "Personal",
    tpa: "1802333409@trucard",
  },
  {
    consumerName: "Consumer 19",
    assets: {
      total: "₹28484",
      gold: "57.76g",
      silver: "19.38g",
      money: "₹453.93",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 19",
    associate: "Associate 19",
    zone: "South",
    accountType: "Business",
    tpa: "8682145275@trucard",
  },
  {
    consumerName: "Consumer 20",
    assets: {
      total: "₹34850",
      gold: "0.35g",
      silver: "45.43g",
      money: "₹77.27",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 20",
    associate: "Associate 20",
    zone: "North",
    accountType: "Personal",
    tpa: "3092104793@trucard",
  },
  {
    consumerName: "Consumer 21",
    assets: {
      total: "₹30873",
      gold: "91.82g",
      silver: "8.76g",
      money: "₹95.34",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 21",
    associate: "Associate 21",
    zone: "South",
    accountType: "Business",
    tpa: "8641276066@trucard",
  },
  {
    consumerName: "Consumer 22",
    assets: {
      total: "₹42088",
      gold: "71.25g",
      silver: "23.61g",
      money: "₹4.21",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 22",
    associate: "Associate 22",
    zone: "North",
    accountType: "Personal",
    tpa: "9683464229@trucard",
  },
  {
    consumerName: "Consumer 23",
    assets: {
      total: "₹7205",
      gold: "82.45g",
      silver: "9.12g",
      money: "₹306.96",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 23",
    associate: "Associate 23",
    zone: "South",
    accountType: "Business",
    tpa: "4785071358@trucard",
  },
  {
    consumerName: "Consumer 24",
    assets: { total: "₹149", gold: "2.53g", silver: "8.74g", money: "₹234.14" },
    kycStatus: "Done",
    fieldExec: "Field Executive 24",
    associate: "Associate 24",
    zone: "North",
    accountType: "Personal",
    tpa: "6702752041@trucard",
  },
  {
    consumerName: "Consumer 25",
    assets: {
      total: "₹36399",
      gold: "10.43g",
      silver: "41.18g",
      money: "₹42.51",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 25",
    associate: "Associate 25",
    zone: "South",
    accountType: "Business",
    tpa: "9846136844@trucard",
  },
  {
    consumerName: "Consumer 26",
    assets: {
      total: "₹17897",
      gold: "49.00g",
      silver: "48.30g",
      money: "₹168.44",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 26",
    associate: "Associate 26",
    zone: "North",
    accountType: "Personal",
    tpa: "3005229039@trucard",
  },
  {
    consumerName: "Consumer 27",
    assets: {
      total: "₹25491",
      gold: "50.18g",
      silver: "18.46g",
      money: "₹210.29",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 27",
    associate: "Associate 27",
    zone: "South",
    accountType: "Business",
    tpa: "4468959901@trucard",
  },
  {
    consumerName: "Consumer 28",
    assets: {
      total: "₹41824",
      gold: "49.74g",
      silver: "20.62g",
      money: "₹100.49",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 28",
    associate: "Associate 28",
    zone: "North",
    accountType: "Personal",
    tpa: "8591538075@trucard",
  },
  {
    consumerName: "Consumer 29",
    assets: {
      total: "₹48806",
      gold: "80.35g",
      silver: "28.78g",
      money: "₹219.36",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 29",
    associate: "Associate 29",
    zone: "South",
    accountType: "Business",
    tpa: "3553270966@trucard",
  },
  {
    consumerName: "Consumer 30",
    assets: {
      total: "₹38091",
      gold: "43.15g",
      silver: "23.84g",
      money: "₹359.85",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 30",
    associate: "Associate 30",
    zone: "North",
    accountType: "Personal",
    tpa: "2324687212@trucard",
  },
  {
    consumerName: "Consumer 31",
    assets: {
      total: "₹42919",
      gold: "24.57g",
      silver: "43.44g",
      money: "₹32.13",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 31",
    associate: "Associate 31",
    zone: "South",
    accountType: "Business",
    tpa: "9502634094@trucard",
  },
  {
    consumerName: "Consumer 32",
    assets: {
      total: "₹14820",
      gold: "92.65g",
      silver: "49.30g",
      money: "₹353.99",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 32",
    associate: "Associate 32",
    zone: "North",
    accountType: "Personal",
    tpa: "8727033836@trucard",
  },
  {
    consumerName: "Consumer 33",
    assets: {
      total: "₹41424",
      gold: "8.92g",
      silver: "11.05g",
      money: "₹23.33",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 33",
    associate: "Associate 33",
    zone: "South",
    accountType: "Business",
    tpa: "2120033526@trucard",
  },
  {
    consumerName: "Consumer 34",
    assets: {
      total: "₹20630",
      gold: "51.14g",
      silver: "21.00g",
      money: "₹346.19",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 34",
    associate: "Associate 34",
    zone: "North",
    accountType: "Personal",
    tpa: "4850973666@trucard",
  },
  {
    consumerName: "Consumer 35",
    assets: {
      total: "₹40086",
      gold: "26.94g",
      silver: "37.56g",
      money: "₹94.39",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 35",
    associate: "Associate 35",
    zone: "South",
    accountType: "Business",
    tpa: "7286683667@trucard",
  },
  {
    consumerName: "Consumer 36",
    assets: {
      total: "₹32176",
      gold: "57.39g",
      silver: "38.32g",
      money: "₹31.97",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 36",
    associate: "Associate 36",
    zone: "North",
    accountType: "Personal",
    tpa: "4387286473@trucard",
  },
  {
    consumerName: "Consumer 37",
    assets: {
      total: "₹26738",
      gold: "29.91g",
      silver: "23.71g",
      money: "₹395.76",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 37",
    associate: "Associate 37",
    zone: "South",
    accountType: "Business",
    tpa: "9029218353@trucard",
  },
  {
    consumerName: "Consumer 38",
    assets: {
      total: "₹9236",
      gold: "63.92g",
      silver: "21.98g",
      money: "₹319.55",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 38",
    associate: "Associate 38",
    zone: "North",
    accountType: "Personal",
    tpa: "5324501223@trucard",
  },
  {
    consumerName: "Consumer 39",
    assets: {
      total: "₹10117",
      gold: "45.98g",
      silver: "8.94g",
      money: "₹484.06",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 39",
    associate: "Associate 39",
    zone: "South",
    accountType: "Business",
    tpa: "2024437085@trucard",
  },
  {
    consumerName: "Consumer 40",
    assets: {
      total: "₹42518",
      gold: "14.93g",
      silver: "47.32g",
      money: "₹384.91",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 40",
    associate: "Associate 40",
    zone: "North",
    accountType: "Personal",
    tpa: "509115729@trucard",
  },
  {
    consumerName: "Consumer 41",
    assets: {
      total: "₹20279",
      gold: "99.34g",
      silver: "36.56g",
      money: "₹152.91",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 41",
    associate: "Associate 41",
    zone: "South",
    accountType: "Business",
    tpa: "693524948@trucard",
  },
  {
    consumerName: "Consumer 42",
    assets: {
      total: "₹25769",
      gold: "97.57g",
      silver: "6.29g",
      money: "₹179.18",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 42",
    associate: "Associate 42",
    zone: "North",
    accountType: "Personal",
    tpa: "1188997504@trucard",
  },
  {
    consumerName: "Consumer 43",
    assets: {
      total: "₹46621",
      gold: "10.40g",
      silver: "36.25g",
      money: "₹211.98",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 43",
    associate: "Associate 43",
    zone: "South",
    accountType: "Business",
    tpa: "9778158883@trucard",
  },
  {
    consumerName: "Consumer 44",
    assets: {
      total: "₹29447",
      gold: "30.81g",
      silver: "48.08g",
      money: "₹196.27",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 44",
    associate: "Associate 44",
    zone: "North",
    accountType: "Personal",
    tpa: "2552171735@trucard",
  },
  {
    consumerName: "Consumer 45",
    assets: {
      total: "₹41853",
      gold: "53.43g",
      silver: "42.31g",
      money: "₹499.17",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 45",
    associate: "Associate 45",
    zone: "South",
    accountType: "Business",
    tpa: "9598164345@trucard",
  },
  {
    consumerName: "Consumer 46",
    assets: {
      total: "₹7525",
      gold: "89.88g",
      silver: "22.68g",
      money: "₹334.35",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 46",
    associate: "Associate 46",
    zone: "North",
    accountType: "Personal",
    tpa: "1345731007@trucard",
  },
  {
    consumerName: "Consumer 47",
    assets: {
      total: "₹18485",
      gold: "97.49g",
      silver: "14.60g",
      money: "₹144.05",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 47",
    associate: "Associate 47",
    zone: "South",
    accountType: "Business",
    tpa: "5747039989@trucard",
  },
  {
    consumerName: "Consumer 48",
    assets: {
      total: "₹4621",
      gold: "0.32g",
      silver: "15.65g",
      money: "₹44.97",
    },
    kycStatus: "Done",
    fieldExec: "Field Executive 48",
    associate: "Associate 48",
    zone: "North",
    accountType: "Personal",
    tpa: "9251457059@trucard",
  },
  {
    consumerName: "Consumer 49",
    assets: {
      total: "₹43132",
      gold: "57.70g",
      silver: "45.06g",
      money: "₹188.81",
    },
    kycStatus: "Pending",
    fieldExec: "Field Executive 49",
    associate: "Associate 49",
    zone: "South",
    accountType: "Business",
    tpa: "4819121347@trucard",
  },
];

// export const chartData = {
//   wed: 0,
//   thu: 500,
//   fri: 300,
//   sat: 730,
//   sun: 240,
//   mon: 270,
//   tue: 800,
// };

export const chartData = [
  {
    id: 1,
    day: "wed",
    purchaseTotal: 0,
  },
  {
    id: 2,
    day: "thu",
    purchaseTotal: 500,
  },
  {
    id: 3,
    day: "fri",
    purchaseTotal: 300,
  },
  {
    id: 4,
    day: "sat",
    purchaseTotal: 730,
  },
  {
    id: 5,
    day: "sun",
    purchaseTotal: 240,
  },
  {
    id: 6,
    day: "mon",
    purchaseTotal: 270,
  },
  {
    id: 7,
    day: "tue",
    purchaseTotal: 800,
  },
];

export const consumerAnalysisData = [
  {
    type: "very Active",
    value: 2500,
  },
  {
    type: "Moderately Active",
    value: 6000,
  },
  {
    type: "Least Active",
    value: 10070,
  },
];

export const customLabels = [
  {
    consumer: "Anjali Singh",
    revenue: "$580K",
    amount: "$750K",
    consumption: "Buy",
    stock: "24k Gold 32g",
    date: "03-10-22",
  },
  {
    consumer: "Jayant Vashisth",
    revenue: "$980K",
    amount: "$750K",
    consumption: "Buy",
    stock: "24k Gold 32g",
    date: "03-10-22",
  },
  {
    consumer: "Rohan Sharma",
    revenue: "$980K",
    amount: "$550K",
    consumption: "Buy",
    stock: "24k Gold 32g",
    date: "03-10-22",
  },
  {
    consumer: "Aman Tanwar",
    revenue: "$380K",
    amount: "$640K",
    consumption: "Buy",
    stock: "24k Gold 32g",
    date: "03-10-22",
  },
  {
    consumer: "Virat Kohli",
    revenue: "$780K",
    amount: "$360K",
    consumption: "Buy",
    stock: "24k Gold 132g",
    date: "03-10-22",
  },
];
